apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webui-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.webui.storage }}
