apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ollama
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: {{ .Values.ollama.service.port }}
  type: ClusterIP
