apiVersion: v1
kind: Service
metadata:
  name: webui-service
  namespace: {{ .Values.namespace }}
  labels:
    app: open-webui
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
    - port: {{ .Values.webui.service.port }}
      targetPort: {{ .Values.webui.service.port }}
      nodePort: {{ .Values.webui.service.nodePort }}
